# Generated by Django 5.1.2 on 2024-10-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-search_date'],
            },
        ),
    ]
